### This script performs a PCA (R-verified)

In [1]:
%load_ext rpy2.ipython
%config InlineBackend.figure_format = 'retina'

import pandas as pd
from sklearn.decomposition import FactorAnalysis
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

import warnings
warnings.filterwarnings('ignore')

#### set directory and import dataset

In [2]:
datadir = '/Volumes/Maxtor/phdresearch/som_new/'
outdir = '/Volumes/Maxtor/phdresearch/som_new/'

In [3]:
data = pd.read_csv(datadir + 'SAfr_700hpa_era_newAB.csv',names = ['0,0','0,1','0,2','1,0','1,1','1,2','2,0','2,1','2,2','3,0','3,1'
         ,'3,2','MEI_AVG','AAO_AVG','ITCZInt_AVG','MJO_AVG','DMI_AVG'])

#### select specific columns in dataset

In [4]:
df = data.iloc[:,0:15]

In [5]:
type(df); df.head()

,"0,0","0,1","0,2","1,0","1,1","1,2","2,0","2,1","2,2","3,0","3,1","3,2",MEI_AVG,AAO_AVG,ITCZInt_AVG
JFM80,0,0,6,0,5,9,8,5,13,12,20,13,0.652,-0.950,6.093
FMA80,0,2,6,4,6,13,7,5,9,11,16,11,0.729,-1.491,6.427
MAM80,8,9,10,7,3,12,6,6,8,8,8,7,0.853,-1.324,6.113
AMJ80,15,15,9,9,6,13,6,6,5,6,0,1,0.925,-0.754,5.903
MJJ80,15,15,20,6,7,16,3,5,5,0,0,0,0.872,-0.712,6.273

#### extract values at each node of the SOM frequency dataset

In [6]:
nodes = ['0,0','0,1','0,2','1,0','1,1','1,2','2,0','2,1','2,2','3,0','3,1'
         ,'3,2','MEI_AVG','AAO_AVG','ITCZInt_AVG']

## Separating out the nodes
x = df.loc[:, nodes].values

# Standardizing the nodes
x = StandardScaler().fit_transform(x)

In [7]:
type (x); x.shape      #x type is a numpy array

(406, 15)

#### perform factor analysis with varimax rotation

In [8]:
era = FactorAnalysis(n_components=3, rotation='varimax').fit(x)

In [9]:
era.get_covariance();

In [10]:
era.components_.T

array([[-0.81502447, -0.03480992,  0.02812297],
       [-0.82913934,  0.11197453,  0.19759255],
       [-0.68419625,  0.36594673,  0.29815912],
       [-0.6794119 ,  0.05111988, -0.28662233],
       [-0.30974335,  0.4438227 , -0.29076044],
       [-0.00837923,  0.72039307,  0.03095742],
       [-0.11678019, -0.09102721, -0.68182675],
       [ 0.4544653 ,  0.09565417, -0.4286571 ],
       [ 0.66459206,  0.2858315 ,  0.19576088],
       [ 0.54842232, -0.55911666, -0.10681822],
       [ 0.73261859, -0.48129461,  0.19716769],
       [ 0.74314022, -0.2576395 ,  0.29560811],
       [-0.23096913,  0.54929702,  0.0923048 ],
       [ 0.06120481, -0.06960255,  0.23025851],
       [ 0.09859103, -0.19750385, -0.0816199 ]])

In [17]:
era_scores = era.transform(x)

In [12]:
#scoresy = era.fit_transform(x); print(scoresy)

In [18]:
df_scores = pd.DataFrame(era_scores,columns = ['RC1', 'RC2','RC3'])
df_scores

          RC1       RC2       RC3
0    1.156191 -0.060210  0.422885
1    0.844915  0.176111  0.122292
2   -0.007165  0.132582  0.319812
3   -0.766558  0.268395  0.047018
4   -0.901574  0.825561  0.736015
5   -0.679149  1.189052  0.916992
6   -0.630750  0.894283  0.483377
7   -1.006724  0.040748  0.280071
8   -0.740854 -0.348403 -1.077929
9   -0.009384 -0.601458 -0.970929
10   0.605337 -0.572052 -1.754807
11   1.052212 -0.949708 -0.181153
12   1.201719 -0.484352  0.139542
13   1.318652 -0.315267  0.654149
14   0.878787  0.053229 -0.033957
15  -0.038200  0.004654 -0.481832
16  -0.714040 -0.369275 -0.960313
17  -0.958986 -0.443860 -1.647119
18  -0.766878 -0.666025 -1.595422
19  -0.371536 -0.317792 -1.877259
20   0.109308 -0.108617 -1.645994
21   0.753991  0.289382 -1.696287
22   1.068474 -0.308546 -0.871002
23   1.255628 -1.033380  0.290672
24   1.275816 -1.365044  0.972736
25   1.185759 -0.847411  0.730952
26   0.656202  0.115447 -0.520004
27  -0.478169 -0.005541 -0.645255
28  -0.719218  0.472195 -0.546863
29  -1.059144  0.225582  0.338618
..        ...       ...       ...
376 -0.224344  0.124323 -1.440372
377 -0.229209  0.046643 -1.258213
378 -0.590703 -0.093934 -0.078989
379 -0.932831 -0.931978 -0.513369
380 -0.707477 -1.249752 -1.113402
381  0.391204 -1.048604 -1.682425
382  0.755488 -0.996164 -0.901753
383  1.035764 -1.464957  0.095764
384  0.973437 -1.219065  0.487493
385  0.935108 -0.406790  0.224354
386  0.147480  0.392697  0.292129
387 -0.621662  0.343391  0.080971
388 -1.077070 -0.114089 -0.510202
389 -1.394117 -0.735208 -0.792508
390 -1.717423 -1.142863 -0.133099
391 -1.532328 -1.084811  0.406728
392 -0.622148 -0.010696 -0.279190
393  0.684919  0.225241 -0.822094
394  0.836447  0.451096 -0.703400
395  0.958161 -0.183507  0.097520
396  0.719898  0.667919  0.532785
397  0.576842  0.846532  0.632510
398 -0.311805  0.992195  0.854342
399 -1.267907  0.055978  0.533156
400 -1.768081 -0.693956  0.551283
401 -1.650335 -1.067270 -0.319055
402 -1.737664 -1.318632 -0.456815
403 -1.529396 -0.687136 -0.458902
404 -0.869599 -0.476877 -0.383620
405  0.240002  0.287921 -0.399668

[406 rows x 3 columns]

In [15]:
mat_loc = '/Volumes/Maxtor/CMIP5_models/cmip5_smhi/cmip_trbi/roll_freq_matrix/'

In [ ]:
mat_rix =  pd.read_csv(mat_loc + 'zg700_day_CanESM2_rcp85_r1i1p1_19800101-20131231_matrix.csv'